import React from 'react';
import { ChevronDown } from 'lucide-react';

interface Alert {
  id: string;
  title: string;
  severity: 'Critical' | 'High';
  status: 'Investigating' | 'Resolved' | 'In Progress';
  date: string;
  time: string;
  description: string;
  source: string;
  engineer: string;
  responsePlan: string;
  events: Array<{
    time: string;
    description: string;
  }>;
  mitigation: string;
}

const CriticalAlertsTimeline = () => {
  const alerts: Alert[] = [
    {
      id: 'alert-001',
      title: 'Multiple Failed Admin Login Attempts',
      severity: 'Critical',
      status: 'Investigating',
      date: 'Dec 15, 2024',
      time: '14:32:45',
      description: 'Automated detection system identified multiple consecutive failed login attempts (15+) from IP 192.168.1.100',
      source: 'Security Monitoring Tool',
      engineer: 'Priya Sharma',
      responsePlan: 'Immediate Response Plan',
      events: [
        { time: '14:32', description: 'First failed attempt detected by IDS' },
        { time: '14:33', description: 'Alert generated by SOC system' },
        { time: '14:35', description: 'Threat assessment by SOC analyst' },
        { time: '14:37', description: 'IP address blocked via firewall' },
        { time: '14:40', description: 'Account temporarily locked' },
        { time: '14:45', description: 'Incident escalated to Tier 2' },
        { time: '14:50', description: 'Forensic analysis initiated' }
      ],
      mitigation: 'IP blocked, account monitoring enabled, Credential monitoring ongoing'
    },
    {
      id: 'alert-002',
      title: 'Ransomware Signature Detection',
      severity: 'Critical',
      status: 'Resolved',
      date: 'Dec 14, 2024',
      time: '09:15:22',
      description: 'Endpoint protection detected ransomware signature on workstation WS-DEV-012',
      source: 'Endpoint Security - AV2 Heuristic Kit',
      engineer: 'Amit Patel',
      responsePlan: 'Ransomware Incident Response Playbook',
      events: [
        { time: '09:15', description:'Ransomware signature detected by endpoint' },
        { time: '09:16', description:'Workstation isolated from network' },
        { time: '09:18', description:'SOC analyst notified' },
        { time: '09:20', description:'Backup snapshots taken activated' },
        { time: '09:25', description:'Malware samples extracted' },
        { time: '09:30', description:'System reimaged, credential reset' },
        { time: '09:45', description:'Network segregation analysis completed' }
      ],
      mitigation: 'Workstation isolated, Backups restored, Perimeter firewall updated'
    },
    {
      id: 'alert-003',
      title: 'Unauthorized Database Access',
      severity: 'High',
      status: 'In Progress',
      date: 'Dec 13, 2024',
      time: '16:45:33',
      description: 'Unusual data access pattern detected on production client database',
      source: 'Database Access Logs - PROD_DB_01',
      engineer: 'Rajesh Kumar',
      responsePlan: 'Data Access Incident Response Plan',
      events: [
        { time: '16:45', description:'Unusual access pattern spotted on-network' },
        { time: '16:47', description:'DLP alarm triggered by SOC' },
        { time: '16:50', description:'Database access suspended' },
        { time: '16:55', description:'Account audit initiated' },
        { time: '17:00', description:'Management contacted - Credential monitoring' },
        { time: '17:10', description:'Audit trail created using SIEM solution' }
      ],
      mitigation: 'Most access: Suspected unauthorized activity, technology-rule updated'
    }
  ];

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'Critical':
        return 'bg-red-600 text-white';
      case 'High':
        return 'bg-orange-100 text-orange-700 border border-orange-200';
      default:
        return 'bg-gray-100 text-gray-700';
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Investigating':
        return 'bg-yellow-100 text-yellow-800';
      case 'Resolved':
        return 'bg-gray-900 text-white';
      case 'In Progress':
        return 'bg-blue-100 text-blue-700';
      default:
        return 'bg-gray-100 text-gray-700';
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 p-8">
      <div className="max-w-[1600px] mx-auto">
        {/* Header */}
        <h1 className="text-2xl font-semibold text-gray-900 mb-6">Critical Alerts Timeline</h1>

        {/* Alert Cards */}
        <div className="space-y-4">
          {alerts.map((alert) => (
            <div key={alert.id} className="bg-white rounded-lg border border-gray-200">
              {/* Card Header */}
              <div className="px-6 py-4 border-b border-gray-200">
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-3">
                    <h2 className="text-base font-semibold text-gray-900">{alert.title}</h2>
                    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getSeverityColor(alert.severity)}`}>
                      {alert.severity}
                    </span>
                    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusColor(alert.status)}`}>
                      {alert.status}
                    </span>
                  </div>
                  <button className="text-gray-400 hover:text-gray-600">
                    <ChevronDown className="w-5 h-5" />
                  </button>
                </div>
                <div className="mt-2 text-xs text-gray-600">
                  Alert Date: {alert.date} - {alert.time}
                </div>
                <p className="mt-2 text-sm text-gray-700">{alert.description}</p>
              </div>

              {/* Content */}
              <div className="px-6 py-5">
                <div className="grid grid-cols-3 gap-8 mb-5">
                  {/* Source */}
                  <div>
                    <div className="text-xs font-semibold text-gray-900 mb-1">Source</div>
                    <div className="text-sm text-gray-700">{alert.source}</div>
                  </div>

                  {/* Engineer */}
                  <div>
                    <div className="text-xs font-semibold text-gray-900 mb-1">Engineer</div>
                    <div className="text-sm text-gray-700">{alert.engineer}</div>
                  </div>

                  {/* Response Plan */}
                  <div>
                    <div className="text-xs font-semibold text-gray-900 mb-1">Response Plan</div>
                    <div className="text-sm text-gray-700">{alert.responsePlan}</div>
                  </div>
                </div>

                {/* Timeline Events */}
                <div className="mb-5">
                  <div className="text-xs font-semibold text-gray-900 mb-3">Timeline</div>
                  <div className="space-y-2">
                    {alert.events.map((event, idx) => (
                      <div key={idx} className="flex items-start gap-3">
                        <div className="flex items-center gap-2 min-w-[60px]">
                          <div className="w-1.5 h-1.5 rounded-full bg-gray-400 flex-shrink-0"></div>
                          <span className="text-xs font-medium text-gray-600">{event.time}</span>
                        </div>
                        <span className="text-sm text-gray-700">{event.description}</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Mitigation */}
                <div>
                  <div className="text-xs font-semibold text-gray-900 mb-2">Mitigation</div>
                  <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
                    <p className="text-sm text-blue-900">{alert.mitigation}</p>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export  {CriticalAlertsTimeline};