import React, { useState } from 'react';
import { MoreVertical, ChevronDown, ChevronRight } from 'lucide-react';

interface RiskItem {
  name: string;
  status: string;
  details?: string;
  statusType?: 'Completed' | 'In Progress' | 'Pending' | 'Overdue';
}

interface MetricCard {
  value: string;
  label: string;
}

interface RiskReport {
  id: string;
  title: string;
  quarter: string;
  high: string;
  reportDate: string;
  generatedBy: string;
  reviewer: string;
  approvedDate: string;
  items: RiskItem[];
  metrics: MetricCard[];
  isExpanded: boolean;
}

const GRCRiskReporting = () => {
  const [reports, setReports] = useState<RiskReport[]>([
    {
      id: '1',
      title: 'Quarterly Risk Assessment Report',
      quarter: 'Q1 Report',
      high: 'High',
      reportDate: 'Report Date: Q4, 2024-01-31',
      generatedBy: 'Generated By: Risk Analytics System',
      reviewer: 'Reviewed: Signed Off By CISO',
      approvedDate: 'Approved: 2025-01-20',
      isExpanded: false,
      items: [
        { name: 'Risk Overview', status: 'Completed', statusType: 'Completed' },
        { name: 'Regulatory Compliance', details: 'SEBI, RBI, IRDAI', statusType: 'Completed', status: 'Status: Compliant' },
        { name: 'Top Risk Register', details: 'Risk Prioritized Actions', statusType: 'In Progress', status: 'In Progress' },
        { name: 'Active Risk Score', details: 'Risk Risk Indicators', statusType: 'Pending', status: 'Pending' },
        { name: 'Risk Metrics Summary', status: '', statusType: 'Pending' }
      ],
      metrics: [
        { value: '42', label: 'Total Risks' },
        { value: '3', label: 'Critical' },
        { value: '15', label: 'High' },
        { value: '24', label: 'Medium/Low' }
      ]
    },
    {
      id: '2',
      title: 'Risk Management Framework Update',
      quarter: 'Monthly',
      high: 'Status',
      reportDate: 'Report Date: Q4, 2024-12-15',
      generatedBy: 'Generated By: Risk & Governance Team',
      reviewer: 'Reviewed: Board Risk Committee',
      approvedDate: 'Approved: 2024-12-28',
      isExpanded: false,
      items: [
        { name: 'Risk Review', status: 'Completed', statusType: 'Completed' },
        { name: 'Framework Review', details: 'NIST CSF, ISO', statusType: 'Completed', status: 'Status: Done' },
        { name: 'Methodology Changes', details: 'Assessment Standards', statusType: 'In Progress', status: 'In Progress' },
        { name: 'Implementation Timeline', details: 'Roll Out Q1', statusType: 'In Progress', status: 'In Progress' },
        { name: 'Risk Metrics Summary', status: '', statusType: 'Pending' }
      ],
      metrics: [
        { value: '85', label: 'Framework Score' },
        { value: '12', label: 'Updates' },
        { value: '95', label: 'Compliance %' },
        { value: '8', label: 'Action Items' }
      ]
    },
    {
      id: '3',
      title: 'Incident Related Risk Update',
      quarter: 'Q2',
      high: 'High',
      reportDate: 'Report Date: Q4, 2024-10-31',
      generatedBy: 'Generated By: Incident Response Officer Team',
      reviewer: 'Reviewed: CRO',
      approvedDate: 'Approved: 2024-11-15',
      isExpanded: false,
      items: [
        { name: 'Incident Summary', details: 'Risk Impact Assessment', statusType: 'Completed', status: 'Completed' },
        { name: 'Control Effectiveness Review', details: 'Control Lessons', statusType: 'Pending', status: 'Pending' },
        { name: 'Risk Register Updates', status: 'Pending', statusType: 'Pending' },
        { name: 'Risk Metrics Summary', status: '', statusType: 'Pending' }
      ],
      metrics: [
        { value: '5', label: '# Incidents' },
        { value: '1', label: 'Critical' },
        { value: '4', label: 'Resolved' },
        { value: '0', label: 'Open' }
      ]
    }
  ]);

  const toggleExpand = (id: string) => {
    setReports(reports.map(report => 
      report.id === id ? { ...report, isExpanded: !report.isExpanded } : report
    ));
  };

  const getStatusColor = (statusType?: string) => {
    switch (statusType) {
      case 'Completed':
        return 'bg-gray-900 text-white';
      case 'In Progress':
        return 'bg-gray-900 text-white';
      case 'Pending':
        return 'bg-gray-400 text-white';
      case 'Overdue':
        return 'bg-red-500 text-white';
      default:
        return 'bg-gray-300 text-gray-800';
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
          <h1 className="text-2xl font-bold text-gray-900">GRC Risk Reporting</h1>
          <button className="px-4 py-2 bg-black text-white rounded text-sm hover:bg-gray-800 transition-colors">
            Generate Report
          </button>
        </div>
      </div>

      {/* Reports List */}
      <div className="max-w-7xl mx-auto px-6 py-6 space-y-6">
        {reports.map((report) => (
          <div key={report.id} className="bg-white rounded-lg border border-gray-200 overflow-hidden">
            {/* Report Header */}
            <div className="p-6">
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-start gap-3 flex-1">
                  <button
                    onClick={() => toggleExpand(report.id)}
                    className="mt-1 text-gray-400 hover:text-gray-600"
                  >
                    {report.isExpanded ? <ChevronDown size={20} /> : <ChevronRight size={20} />}
                  </button>
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-2">
                      <h2 className="text-lg font-semibold text-gray-900">{report.title}</h2>
                      <span className="px-3 py-1 bg-gray-200 text-gray-800 rounded text-xs font-medium">
                        {report.quarter}
                      </span>
                      <span className="px-3 py-1 bg-gray-200 text-gray-800 rounded text-xs font-medium">
                        {report.high}
                      </span>
                    </div>
                    <div className="flex flex-wrap gap-4 text-xs text-gray-600">
                      <span>{report.reportDate}</span>
                      <span>{report.generatedBy}</span>
                      <span>{report.reviewer}</span>
                      <span>{report.approvedDate}</span>
                    </div>
                  </div>
                </div>
                <button className="text-gray-400 hover:text-gray-600">
                  <MoreVertical size={20} />
                </button>
              </div>

              {/* Progress Bar */}
              <div className="mb-6">
                <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-gradient-to-r from-gray-900 to-gray-700"
                    style={{ width: '75%' }}
                  />
                </div>
              </div>

              {/* Report Items */}
              <div className="space-y-2 mb-6">
                {report.items.map((item, idx) => (
                  <div key={idx} className="flex items-center justify-between py-2">
                    <div className="flex items-center gap-3 flex-1">
                      <span className="text-sm text-gray-700">{item.name}</span>
                      {item.details && (
                        <>
                          <span className={`px-2 py-0.5 rounded text-xs font-medium ${getStatusColor(item.statusType)}`}>
                            {item.status}
                          </span>
                          <span className="text-xs text-gray-500">{item.details}</span>
                        </>
                      )}
                    </div>
                    {item.statusType && !item.details && (
                      <span className={`px-3 py-1 rounded-full text-xs font-medium ${getStatusColor(item.statusType)}`}>
                        {item.status}
                      </span>
                    )}
                  </div>
                ))}
              </div>

              {/* Metrics */}
              <div className="grid grid-cols-4 gap-8 pt-6 border-t border-gray-200">
                {report.metrics.map((metric, idx) => (
                  <div key={idx} className="text-center">
                    <div className="text-3xl font-bold text-gray-900">{metric.value}</div>
                    <div className="text-xs text-gray-500 mt-1">{metric.label}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Expanded Content */}
            {report.isExpanded && (
              <div className="bg-gray-50 border-t border-gray-200 p-6">
                <h3 className="text-sm font-semibold text-gray-700 mb-4">Risk Assessment Details</h3>
                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-white p-4 rounded border border-gray-200">
                    <div className="text-xs text-gray-500 mb-1">Assessment Period</div>
                    <div className="text-sm font-medium text-gray-900">Q4 2024</div>
                  </div>
                  <div className="bg-white p-4 rounded border border-gray-200">
                    <div className="text-xs text-gray-500 mb-1">Next Review</div>
                    <div className="text-sm font-medium text-gray-900">2025-04-15</div>
                  </div>
                  <div className="bg-white p-4 rounded border border-gray-200">
                    <div className="text-xs text-gray-500 mb-1">Risk Trend</div>
                    <div className="text-sm font-medium text-green-600">↓ Decreasing</div>
                  </div>
                  <div className="bg-white p-4 rounded border border-gray-200">
                    <div className="text-xs text-gray-500 mb-1">Overall Status</div>
                    <div className="text-sm font-medium text-blue-600">On Track</div>
                  </div>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

export  {GRCRiskReporting};